#!/bin/bash

LD_LIBRARY_PATH=/opt/cura2/lib PYTHONPATH=/opt/cura2/lib/python3/dist-packages QT_PLUGIN_PATH=/opt/cura2/lib/plugins QML2_IMPORT_PATH=/opt/cura2/lib/qml QT_QPA_FONTDIR=/opt/cura2/lib/fonts /usr/bin/python3 /opt/cura2/bin/cura2 "$@"
